# Global sandbox settings shared across all mkApp instances.
#
# The per-app backend/storage options live on modules.apps.<name>.sandbox.*
# (generated by lib/apps.nix). This module holds the fleet-wide knobs, the shared
# /<tier>/sandbox parent directories, the polkit rule for the systemd-stash
# backend, and the one-time data migration into the stash layout.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.modules.sandbox;

  # Exact allowlist of the REAL sandbox-<app>.service units, for the polkit rule
  # below. Sourced from modules.sandbox.units (each backend emits its own unit name)
  # rather than scanning services by "sandbox-" prefix — an explicit list doesn't
  # implicitly reserve the prefix for any future unrelated sandbox-* unit. A prefix
  # match would also have been a root-escalation (manage-units gates
  # StartTransientUnit → `systemd-run --unit=sandbox-evil --uid=0`); the exact list
  # closes that (a transient unit can't reuse a static unit's fragment name).
  allowedUnitsJson = builtins.toJSON cfg.units;

  tierMount = {
    persist = "/persist";
    large = "/large";
    cache = "/cache";
  };

  co = "${pkgs.coreutils}/bin";
  ul = "${pkgs.util-linux}/bin";
  pg = "${pkgs.procps}/bin/pgrep";

  # Per-app migration from the old /<tier>/home/<user>/<path> impermanence layout
  # into /<tier>/sandbox/<app>/<path>. Runs from an activation script, so it fires
  # on `nixos-rebuild switch` (no reboot) AND on boot. Safe on a live system:
  #   - fully idempotent PER ENTRY (no app-level stamp), so a storage entry ADDED
  #     to an already-converted app migrates on the next switch — move only fires
  #     when the source exists and the target is absent/empty;
  #   - if the app is running it DEFERS (don't move data out from under it);
  #   - stale old-layout bind mounts (present after a switch, absent at boot) are
  #     unmounted deepest-first before the move;
  #   - both paths are on the same tier subvol, so `mv` is an atomic rename;
  #   - chowns reconcile ownership (handles same-uid <-> dedicated transitions).
  migrateApp =
    m:
    let
      unmounts = lib.concatMapStringsSep "\n" (
        e:
        let
          t = "/home/${m.user}/${e.path}";
        in
        ''
          if __safe "${t}" && ${ul}/mountpoint -q --nofollow "${t}" 2>/dev/null; then
            ${ul}/umount --no-canonicalize "${t}" 2>/dev/null || ${ul}/umount -l --no-canonicalize "${t}" 2>/dev/null || true
          fi''
      ) (lib.reverseList m.entries); # deepest-first
      moves = lib.concatMapStringsSep "\n" (
        e:
        let
          dst = "${tierMount.${e.tier}}/sandbox/${m.app}/${e.path}";
          # Old-layout data can sit under ANY tier's home: a path being re-tiered
          # (e.g. .claude/security persist→large, or codex logs persist→large) still
          # lives under the parent's OLD tier, not its new declared one. Search the
          # declared tier first, then the others; take the first that exists. Each
          # candidate test is fully quoted, so paths with spaces (Electron's
          # "Code Cache") are safe.
          candidateTiers = [
            e.tier
          ]
          ++ (lib.filter (t: t != e.tier) [
            "persist"
            "large"
            "cache"
          ]);
          srcPick = lib.concatMapStringsSep "\n" (
            t:
            let
              c = "${tierMount.${t}}/home/${m.user}/${e.path}";
            in
            ''if [ -z "$__src" ] && [ -e "${c}" ]; then __src="${c}"; fi''
          ) candidateTiers;
        in
        ''
          __src=""
          ${srcPick}
          # Root moving a jrt-controlled path: refuse if ANY component (not just the
          # leaf) is a symlink — __safe requires the physical realpath to equal the
          # literal path, so a jrt-planted symlink anywhere below /<tier>/home/jrt
          # (e.g. .../Documents -> /elsewhere) can't redirect the root mv into or a
          # symlinked source into the stash (the backend also re-checks the stash type
          # before binding). mv -T never descends into an existing dir.
          if [ -n "$__src" ] && ! __safe "$__src"; then echo "  refusing symlinked source path $__src"; __src=""; fi
          if [ -n "$__src" ]; then
            ${co}/mkdir -p "$(${co}/dirname "${dst}")"
            if [ ! -e "${dst}" ]; then
              echo "  mv ${dst}"; ${co}/mv -T "$__src" "${dst}" || echo "  ERROR moving $__src"
            elif [ -d "${dst}" ] && [ -z "$(${co}/ls -A "${dst}" 2>/dev/null)" ]; then
              ${co}/rmdir "${dst}"; echo "  mv(empty) ${dst}"; ${co}/mv -T "$__src" "${dst}" || echo "  ERROR moving $__src"
            else
              echo "  skip ${e.path} (target non-empty)"
            fi
          fi${
            lib.optionalString (e.tier == "cache") ''

              # Cache is disposable: after migrating the canonical copy, delete any
              # stale duplicates of this EXACT declared path left under the other tiers
              # (the persist/cache desync), so the persist parent move can't sweep them
              # into the backed-up stash. Bounded to declared cache entries only.
              ${lib.concatMapStringsSep "\n" (
                t:
                let
                  c = "${tierMount.${t}}/home/${m.user}/${e.path}";
                in
                ''if __safe "${c}"; then echo "  rm stale cache ${c}"; ${co}/rm -rf "${c}"; fi''
              ) candidateTiers}''
          }''
      ) (lib.reverseList m.entries); # deepest-first: extract carved children before the parent moves
      # Reconcile ownership every run (not gated by the stamp): mv preserves the
      # old jrt ownership, and flipping an app same-uid <-> dedicated changes the
      # target owner. NB: check the WHOLE tree, not just dst's top-dir owner — the
      # dedicated tmpfiles leaf rule chowns the top dir to app-<name> (non-recursively),
      # so a top-owner test would wrongly conclude "already migrated" and leave the
      # children jrt-owned → the app EACCESes on its own data. `find … ! -user … -quit`
      # early-exits at the first mis-owned entry, so it stays cheap once converged.
      chowns = lib.concatMapStringsSep "\n" (
        e:
        let
          dst = "${tierMount.${e.tier}}/sandbox/${m.app}/${e.path}";
        in
        ''
          if [ -e "${dst}" ] && [ -n "$(${pkgs.findutils}/bin/find "${dst}" ! -user "${m.owner}" -print -quit 2>/dev/null)" ]; then
            echo "  chown -R ${m.owner} ${dst}"; ${co}/chown -R "${m.owner}" "${dst}" 2>/dev/null || true
          fi''
      ) m.entries;
    in
    ''
      if ${pg} -x "${m.bin}" >/dev/null 2>&1; then
        : # ${m.app} running — defer the MOVES (mv'ing data from under a live app is
          # unsafe); chowns still run below.
      else
        ${unmounts}
        ${moves}
      fi
      # Ownership reconcile runs EVERY activation, gated on nothing: changing a file's
      # owner never disrupts a running process's open FDs, and gating it on the app
      # being stopped means a dedicated app that happens to be running at switch time
      # never gets its stash chowned off the old (jrt) owner — it then hits EACCES on
      # its OWN data (the lunar-client symptom). Idempotent: skips entries already
      # owned correctly, and no-ops on dst paths that don't exist yet.
      ${chowns}
    '';

  migrateScript = pkgs.writeShellScript "sandbox-stash-migrate" ''
    # A path is safe for a root mv/rm/umount iff it EXISTS and no component is a
    # symlink — its physical realpath must equal the literal path. Guards every
    # destructive/mount op below against a jrt-planted symlink anywhere under
    # /<tier>/home/jrt (or ~) redirecting root at some other host path.
    __safe() { [ -e "$1" ] && [ "$(${co}/realpath -- "$1" 2>/dev/null)" = "$1" ]; }
    ${lib.concatMapStringsSep "\n" migrateApp cfg.stashMigrations}
    exit 0
  '';
in
{
  options.modules.sandbox = {
    gpuDevices = lib.mkOption {
      type = lib.types.nullOr (lib.types.listOf lib.types.str);
      default = null;
      example = [
        "/dev/dri/card1"
        "/dev/dri/renderD129"
        "/dev/nvidia0"
        "/dev/nvidiactl"
        "/dev/nvidia-modeset"
        "/dev/nvidia-uvm"
        "/dev/nvidia-uvm-tools"
      ];
      description = ''
        Device nodes the `gpu` capability binds into app sandboxes. null → the
        default in lib/capabilities-nixpak.nix (all GPUs). Set on multi-GPU
        hosts to expose ONLY the display GPU's nodes: chromium picks the first
        openable /dev/dri/renderD* and NVIDIA Vulkan enumerates every
        /dev/nvidia*, so a visible compute-only card gets chosen for buffer
        allocation and every cross-GPU dmabuf import fails (context-lost loop).
        All entries are bind-try: listing a node absent on some boot is safe.
        Honored by the v2 backends (systemd/nixpak) only — the legacy in-session
        wrap keeps the full default (threading host config into it recurses:
        legacy finalPackage evaluation cycles through config.modules).
      '';
    };

    forceHomeLocation = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Force every app.storage entry across ALL apps to location = "home"
        (data at the normal ~/<path> via impermanence, host-visible), overriding
        per-entry placement and the hidden stash. One switch for debugging,
        inspection, recovery, or a host where hiding isn't wanted. Sandboxing
        itself is unaffected — only the stash placement is disabled.
      '';
    };

    units = lib.mkOption {
      internal = true;
      default = [ ];
      type = lib.types.listOf lib.types.str;
      description = ''
        Exact systemd unit names (sandbox-<app>.service) the stash backends
        generate — emitted explicitly by each backend, consumed by the polkit
        allowlist below. An explicit list, NOT a scan of every service whose name
        starts with "sandbox-" (which would implicitly reserve that prefix and let
        an unrelated future sandbox-* unit inherit the jrt start/stop grant).
      '';
    };

    stashMigrations = lib.mkOption {
      internal = true;
      default = [ ];
      type = lib.types.listOf (
        lib.types.submodule {
          options = {
            app = lib.mkOption { type = lib.types.str; };
            bin = lib.mkOption { type = lib.types.str; };
            user = lib.mkOption { type = lib.types.str; }; # old-layout source user
            owner = lib.mkOption { type = lib.types.str; }; # target stash ownership
            entries = lib.mkOption {
              type = lib.types.listOf (
                lib.types.submodule {
                  options = {
                    tier = lib.mkOption { type = lib.types.str; };
                    path = lib.mkOption { type = lib.types.str; };
                  };
                }
              );
            };
          };
        }
      );
      description = ''
        Internal aggregation (set by the stash backends): per-app stash entries
        whose existing data must be moved once from the old
        /<tier>/home/<user>/<path> impermanence layout into
        /<tier>/sandbox/<app>/<path>. Consumed by the migration activation script.
      '';
    };
  };

  config = {
    # Shared parents of the per-app stashes. Traversable (0711) but NOT itself a
    # lock: the per-app lock lives on /<tier>/sandbox/<app> (see lib/storage.nix).
    # Locking these 0700 root would deny jrt the search bit and break every
    # rootless-nixpak app trying to reach its own stash.
    systemd.tmpfiles.rules = [
      "d /persist/sandbox 0711 root root -"
      "d /large/sandbox   0711 root root -"
      "d /cache/sandbox   0711 root root -"
    ];

    # The systemd-stash backend runs each app as a root-set-up system service
    # (private mount ns + stash graft, then drop to the user). The user triggers
    # it with `systemctl start --wait sandbox-<app>` and stops it on teardown, so
    # allow the desktop user to manage ONLY the exact set of generated
    # sandbox-<app>.service units, and ONLY the verbs that flow actually needs.
    #   - Exact allowlist, NOT a prefix match: manage-units also gates
    #     StartTransientUnit, so `sandbox-*` would let jrt systemd-run an arbitrary
    #     root unit named "sandbox-…". The exact allowlist closes that hole.
    #   - Verb pinned to start/stop/ref: `systemctl start --wait` issues StartUnit
    #     (start) AND RefUnit (ref, to hold the result until the unit exits); stop is
    #     teardown. Everything else manage-units gates — set-property, kill, freeze,
    #     clean, thaw, … — is denied (falls through to the admin default), so this
    #     grant is no broader than the launcher requires.
    security.polkit.extraConfig = ''
      polkit.addRule(function(action, subject) {
        if (action.id == "org.freedesktop.systemd1.manage-units" &&
            subject.user == "jrt") {
          var allowed = ${allowedUnitsJson};
          var unit = action.lookup("unit");
          var verb = action.lookup("verb");
          if (unit && allowed.indexOf(unit) >= 0 &&
              (verb == "start" || verb == "stop" || verb == "ref")) {
            return polkit.Result.YES;
          }
        }
      });
    '';

    # Cross-uid document portal: our xdg-desktop-portal fork mounts the
    # document-portal FUSE with allow_other (overlays/custom-packages.nix) so a
    # dedicated-uid app can read the doc:// files jrt's portal exports. fusermount3
    # refuses an allow_other mount unless user_allow_other is set here — and if the
    # mount is refused the portal fails to start, breaking file dialogs for EVERY
    # sandboxed app, so this and the overlay change are a matched pair.
    programs.fuse.userAllowOther = true;

    # One-time data migration into the stash layout. As an activation script it
    # runs on `nixos-rebuild switch` (no reboot needed) and on boot, before the
    # graphical session — see migrateApp above for the safety properties.
    system.activationScripts.sandbox-stash-migrate = lib.mkIf (cfg.stashMigrations != [ ]) {
      text = "${migrateScript}";
      deps = [ ];
    };
  };
}
